# Generated by Django 5.2.4 on 2025-07-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0002_subject"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fio", models.CharField(max_length=100)),
                ("subject", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="subject",
            name="teacher",
            field=models.ManyToManyField(related_name="fanlar", to="school.teacher"),
        ),
    ]
