# Generated by Django 5.2.4 on 2025-07-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0003_teacher_subject_teacher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="teacher",
        ),
        migrations.AddField(
            model_name="subject",
            name="teachers",
            field=models.ManyToManyField(related_name="fanlar", to="school.teacher"),
        ),
    ]
